### ISSUE TITLE
BA.01 Create Software Design Document

### ISSUE THREAD

**Issue by illia-tss** [tss-ta/tss#110]

**Comment by illia-tss** [comment]
[document template](https://drive.google.com/file/d/0B7wYGqZbn0jGNzJzN0RBMFBJb1E/view?usp=sharing)

**Comment by LisMars** [comment]
UI : http://www.ex.ua/413105170647

**Comment by illia-tss** [comment]
новая версия [SDD](https://drive.google.com/open?id=0B7wYGqZbn0jGMzNRSlhEbDF6RUE&authuser=0)
1. Добавлена Use Case диаграмма для Кастомера.
2. Добавлены несколько Use Case для Администратора и Кастомера.
3. Добавлено высокоуровневое описание структуры приложения.
4. Отображены заготовки для интерфейса Администратора и Кастомера.
5. Добавлена ER-диаграмма.

Некоторые записи оставил из шаблона дабы не рушить структуру документа.

**Comment by LisMars** [comment]
Диаграмма класов дао и связаных , для Кастомера(зделаное на данный момент) http://www.ex.ua/502787893317

**Comment by illia-tss** [comment]
новая версия [SDD](https://drive.google.com/file/d/0B7wYGqZbn0jGYjdoRUlUekxqU2c/view?usp=sharing)
1. Добавлены диаграммы классов для Customer, Administrator workflow.
2. Изменена ER-диаграмма.

**Comment by illia-tss** [comment]
новая версия [SDD](https://drive.google.com/file/d/0B7wYGqZbn0jGUkx4ZHp0a3FXd2c/view?usp=sharing)
Добавлены Use-Case для Administrator, Customer.

**Comment by Rokill** [comment]
Test cases (те которые можно было сделать не текущий момент): [Google Drive](https://drive.google.com/file/d/0B4nI_8tHC0LvajlwWGlBMmZwOHc/view?usp=sharing)
Traceability Matrix: [Google Drive](https://docs.google.com/spreadsheets/d/1E06mXvOf3yLfXC_yykSSL9QHnr6p10W_yWZA_I4G-3w/edit?usp=sharing)
