### ISSUE TITLE
REG.5.1 — System should validate all fields on UI

### ISSUE THREAD

**Issue by olga-tss** [tss-ta/tss#136]
Subtask for the [REG.5](https://github.com/tss-ta/tss/issues/11).

**Comment by maks0** [comment]
are youy really sure that tis issue is well done?

**Comment by olga-tss** [comment]
Partially done.
As agreed with @Rokill, this task should be performed in the next iteration.

**Comment by maks0** [comment]
Adress validation doesn't work in convey corp TO
