### ISSUE TITLE
ER model for Database

### ISSUE THREAD

**Issue by Rokill** [tss-ta/tss#3]
Leave your suggestions here

**Comment by olga-tss** [comment]
Probably we can attach sceenshots (or [PlantUML](http://plantuml.sourceforge.net/) diagrams, for example) of our ERD-ideas to the Wiki.

FYI: there is a [PlantUML plugin](http://plugins.netbeans.org/plugin/49069/plantuml) for Netbeans .

**Comment by Rokill** [comment]
Then we can write all documentation on Wiki (like traceability matrix, ER model, basic plan).

**Comment by illia-tss** [comment]
предлагаю такую модель для нашей DB: https://www.gliffy.com/go/publish/7772301
комментируем, критикуем

**Comment by Rokill** [comment]
Мои предложения по поводу ER модели выше:
- В Adress - customer_id: int <<FK>> - лишнее, оно уже есть в Order (- order_id: int <<FK>>).
- В Celebration - необходимо указать именно не только кол-во машин, а - driver_id всех заказанных машин. Думаю можно просто оформить это как несколько заказов в одной сущ-ти Service.
- Не совсем понимаю зачем сущность Driver_Car? Её можно реализовать добавив в сущность Driver поле car_id. В требованиях об сказано (ROL.3 - Administrator is able to assign driver to a particular car). Т.е. машина у водителя может быть только одна.

В остальном ER модель мне кажется подходящей.

**Comment by olga-tss** [comment]
В дальнейшем нам надо будет делать аутентификацию, авторизацию. Думаю, разумно будет использовать возможности сервера приложений, а не писать собственную логику управления пользователями, ролями и группами.
Наше приложение вполне вписывается в возможности, предоставляемые JBoss AS. Вот описание того, какие должны быть таблицы и столбцы, чтобы JBoss за нас работал с секьюрити: [JDBC Realm](http://docs.jboss.org/jbossweb/3.0.x/realm-howto.html). Вот несколько примеров: [один](http://www.alesandro-lang.com/blog/setup_a_jdbc_realm_inside_openshift/), [второй](http://www.thejavageek.com/2013/09/18/configure-jaas-jboss-7-1-mysql/).
Т. е. таблицы User и Group нужно скорректировать, исходя из вышеприведённого текста, а также нужна будет таблица Role.

**Comment by Rokill** [comment]
Предлагаю следующую ER модель, исправленную на основе замечаний - http://www.gliffy.com/go/publish/7788643

**Comment by olga-tss** [comment]
Я обратила внимание на одну неточность. Там в [документации к jboss-у](http://docs.jboss.org/jbossweb/3.0.x/realm-howto.html) они в таблицах id-шники не используют, а делают так:

``` sql
create table users (
  user_name         varchar(15) not null primary key,
  user_pass         varchar(15) not null
);

create table user_roles (
  user_name         varchar(15) not null,
  role_name         varchar(15) not null,
  primary key (user_name, role_name)
);
```

И вот я думаю, нужны ли нам id-шники или нет, вдруг  jboss хавает только так, как в документации?
И еще вопрос - а где же группы? И куда бы их тут впихнуть?

**Comment by Rokill** [comment]
На счёт id, не уверен, но исправил. Группы тоже. Их можно и как роли реализовать, но пока я оставил как было - отдельно сущностью Group. 
http://www.gliffy.com/go/publish/7788643

**Comment by illia-tss** [comment]
Всех с праздниками!
По поводу "В Adress - customer_id: int <> - лишнее, оно уже есть в Order (- order_id: int <>).": здесь я сохранил айдишник кастомера для возможности ассоциации адресов с конкретным юзером (ROL.6 Customer user can choose the address from his personal list to order a taxi (home address, office address, cafe address)). Это поле в большинстве случаев будет null.
Со всем остальным полностью согласен.

**Comment by Rokill** [comment]
При хранении в адресе id пользователя, выходит дублирование данных (избыточность).
ROL.6 Customer user can choose the address from his personal list to order a taxi - можно реализовать простым SELECT по заказам которые сделал конкретный пользователь, выбрав все адреса на которые он заказывал (если работать с ER которую я выкладывал выше).

**Comment by LisMars** [comment]
Думаю еще нужна таблица для хранения тарифов(время суток, вид транспорта/услуги,цена), а в ТО дату и время поступления заказа(чтобы упорядочено выводить, к недавним можно было оставлять комментарии).Также сохранять для клиентов список  мест( персональные адреса, из которых потом можно будет выбирать куда вызвать такси).

**Comment by maks0** [comment]
тарифы в процентах обрабатывать проще

**Comment by olga-tss** [comment]
Проценты могут быть не всегда. Иногда бывает просто плюс сколько-то там грн., т. е. фиксированная надбавка. Надо подумать, как будет работать модуль вычисления конечной стоимости поездки.
С другой стороны, никогда не поздно поменять поле в таблице. Плюс может кураторы поправят, если что.

**Comment by maks0** [comment]
согласен что не всегда процент удобно для пользователя но тогда нужна отдельная таблица с колонкой типа тарификации (одноразовый, почасовой, по расстоянию) ну и колонку цены, а обработка процентов проще в реализации

**Comment by LisMars** [comment]
В условии ACK11 - The system should provide to set different Taxi Price on one route for different car category, time, day of week., тоесть цуна должна зависеть еще и от времени, дня нидели, транспорта...если все это учитывать в формуле с процентами, то не получится ли слишком запутано?

**Comment by maks0** [comment]
это я не учел, тогда нужна таблица тарифов

**Comment by Rokill** [comment]
Новая версия ER модели - http://www.gliffy.com/go/publish/7788643
По поводу новых предложений:
- добавлено время заказа (booking_time), а order_time - это время на которое клиент ждёт машину.
- На счёт привязки адресов к пользователям у меня сомнения, т.к. как я писал это выше - адреса можно получить select запросом по таблице TaxiOrder. Я думаю этот момент надо у кураторов уточнить, на встрече в четверг.
- По поводу тарифов. Добавлена таблица Tariff и вспомогательная ей CarType. Тарифы в ней зависят от типа автомобиля. 
- На счёт зависимости от времени поездки - поле cost в таблице Tariff отражает стоимость почасового тарифа. 
- А вот связь от дня недели пока не знаю как правильно реализовать, может просто с помощью поля name - "Weekends Tariff", т.е. для каждого автомобиля будут свои тарифы различные по названию. Но это как-то криво выглядит.

**Comment by LisMars** [comment]
Насчет адресов, там условиях есть пункт ROL.6 : Customer User can choose the address from his personal list to order a taxi (home address, office address, café address). Вот для этого помоему и нужно привязывать список адресов к пользователям.

**Comment by bbuallbest** [comment]
Было бы неплохо убрать из адреса поле to/from, вместо этого у TO сделать 2 внешних ключа from_address и to_address.
Так же на данный момент в ТО никак не фигурируют доп. критерии к водителю и машине:

> The system should provide an ability for users to select additional options while ordering taxi:
> - to choose car category (business class, economy class, vans) based on their preference
> -   to choose the way of payment(visa card/ cash)
> -   to choose the sex of driver(male/ female)
> -   to choose a car applicable for animal transportation 
> -   to choose a car with or without free WI-FI in the car
> -   to choose smoking/non-smoking driver
> -   to choose the music style that  user will listen to
> -   to choose the a car with or without air-conditioner

**Comment by Rokill** [comment]
Новая версия ER модели - http://www.gliffy.com/go/publish/7788643
Внесены следующие изменения:
- Добавлена таблица UserAdresses, для привязки адресов к пользователям и выполнения ROL.6 : Customer User can choose the address from his personal list to order a taxi (home address, office address, café address). 
- Удалены поля from/to из Adress, и добавлены from_adress, to_adress ключи в TaxiOrder на соответствующие адреса. 
- Добавлены доп. критерии к заказу в TaxiOrder.

**Comment by maks0** [comment]
sex: VARCHAR2 (male | female) -  может таки bool или целочисленный, насчет музыки тоже не  очень хорошо строкой хранить (или доп таблица или чисиловой), статус, роль, тип гуруппы и т.п. тоже числовые, я так думаю

**Comment by maks0** [comment]
статус тоже числовой, я думаю

**Comment by Rokill** [comment]
Пол (sex: VARCHAR2 (male | female) исправил (http://www.gliffy.com/go/publish/7788643).
А вот с музыкой я так понимаю, что это поле будет инструкцией для водителя отображаемой в его dashboard'e. Исходя из этого думаю текстового описания предпочитаемой музыки должно хватить, чтобы водитель понял какую музыку ему включить при поездке.

**Comment by maks0** [comment]
с музыкой для меньших заморочек можно и варчар, но хранить типы (которые скорее всего будут enum) как текст, по-моему нехорошо, вероятность опечатки программиста (или влепит то чего не предусмотрено) и доп ресурсы на текст, их наверное нужно в число загнать.  Я так понимаю, но лучше было бы чтобы кто-то поопытненнее подтвердил.

**Comment by maks0** [comment]
в car      category: VARCHAR2(business | economy |van) - у нас же уже есть табличка с типом машин, значить туда и ссылаться

**Comment by Rokill** [comment]
А, да. Исправил car category.

**Comment by maks0** [comment]
если есть табличка роли может нужно сделать в 2 столбца, числовой id and name и ссылаться на  id, как предложения, не уверен в 100% правильности такого подхода. Еще зачем в машине (car) musicstyle, что воткнешь то и будет играть?

**Comment by Rokill** [comment]
Там в спецификации JBoss AS (мы выше обсуждали) необходимо именно чтобы username было PK.

**Comment by illia-tss** [comment]
Моя версия базы: http://www.gliffy.com/go/publish/7812659
- Выделил таблицы DriverOption, CarOption для избежания дублирования данных. Когда у TaxiOrder статус "Queued", заполнены поля driver_opt_id и car_opt_id для фиксации заказа. Когда один/несколько драйверов ассайнят на себя заказ (статус "Assigned"), эти поля обнуляются. Из-за того, что драйверов может быть много, из TaxiOrder убрал поле driver_id, а в Driver добавил order_id.
- Пересмотрел логику тарификации. Теперь у каждого пункта, который влияет на ценообразование, есть свое поле price. Переделал таблицу Tariff. В ней будет только одна строка с текущим состоянием тарификации в будни/выходные, в дневное/ночное время, почасовой/покилометровый тариф. У каждого Service тоже есть свои поправки к цене. 
- Добавил таблицу PersonalAddress для прямой ассоциации адреса с юзером (ROL.6 : Customer User can choose the address from his personal list to order a taxi)
- Поисправлял внешние ключи, ассоциированные с пользователями.

**Comment by maks0** [comment]
Илья, так получше, но не пойму насчет тарифа пока, и payment: VARCHAR2 (visa | cash) наверное bool или число

**Comment by illia-tss** [comment]
Есть те сущности, которые влияют на ценообразование: Car_Option, Tariff, Service (и все его наследники). Тарифы всех этих штук может править админ, или какое-либо ответственное лицо. Все они ассоциируются с TO. Тоесть при выборе клиентом того или другого сервиса, в зависимости от дня, времени суток, продолжительности поездки, из этих таблиц будут подтягиваться цены (проценты), которые были заблаговременно установлены админом. После в TO будет формироваться конкретная цена поездки.

**Comment by illia-tss** [comment]
по поводу payment можно поменять)

**Comment by vchekaliuk** [comment]
Поясність, будь ласка, таке (можливо, я десь пропустив це обговорення):
1. Що означають поля у сутності service?
2.  Як планується реалізувати наслідування засобами СУБД?

**Comment by maks0** [comment]
так як я розумію ( може то і не зовсім правильно) то у service додаткові послуги, а щодо 2 то може нащадок буде юзати таблицю-предка. якось дивно, звичайно, але можливо

**Comment by Rokill** [comment]
На счет наследования, в PostgreSQL это реализовано: http://www.postgresql.org/docs/9.1/static/tutorial-inheritance.html.

**Comment by illia-tss** [comment]
> 1. Що означають поля у сутності service?

В табличке Service каждое поле отображает название предоставляемого сервиса и тариф за него. Согласен, смотрится криво =) сделаю там 2 поля: "service_name" и "price"

По поводу наследования, не знал, что у постгреса есть такая фича =) думаю будем ею пользоваться.

**Comment by vchekaliuk** [comment]
Ну там просто додано синтаксис для зменшення кількості коду. А, фактично, використовується додаткова таблиця для нащадка і union у запитах. Чи не має сенс одразу малювати ці додаткові таблички на діаграмі замість наслідування?

**Comment by illia-tss** [comment]
Виталий, дополнительные таблички нарисованы, они красным выделены. Примеры "наследования" брал [отсюда](http://www.agiledata.org/essays/mappingObjects.html)

**Comment by vchekaliuk** [comment]
Кілька коментарів щодо схем
1. Відсутні таблиці/поля для збереження маршруту.
2. Немає таблиці з правами та/або якогось зв'язку між правами користувачами та групами. Користувач може бути у кількох групах, окремі права та ролі можуть бути призначені як користувачам, так і групам.
3. Все ще не зрозуміле призначення таблиці service. Чому сервіс посилається на ТО, а не навпаки? Як знайти інформацію, який саме сервіс присутній у конкретному ТО (як знайти який саме нащадок від service)?
4. Як я зрозумів у таблиці service зберігаються уже оформлені замовлення на сервіси. А де зберігається інформація про власне сервіси  (тарифи, максимальний час замовлення, максимальна кількість машин у замовленні тощо)?
5. У ТО повинна бути інформація як про машину, так і про водія, адже водій надалі може змінити машину і втратиться інформація.
6. Прив'язку водія до машини бажано мати типу багато-до-багатьох із зазначенням періоду (коли адмін призначив і коли зняв водія). Можна використати це для пункту 4.
7. Не всі опціональні сервіси присутні. Для сервісу celebration немає зв'язку з конкретним набором машин, є лише кількість.
8. Немає підтримки кількох адрес, ні опціонально у звичайному замовленні, ні у обов'язковому сервісі із доставки співробітників.

**Comment by illia-tss** [comment]
> Відсутні таблиці/поля для збереження маршруту.

Переделал. Создал новую таблицу для маршрута, соотнес ее с Address. Отношение один-ко-многим.

> Немає таблиці з правами та/або якогось зв'язку між правами користувачами та групами. Користувач може бути у кількох групах, окремі права та ролі можуть бути призначені як користувачам, так і групам.

Роли (Admin, Driver, Customer) вроде ж и подразумевают права. ROL.5 Administrator can assign role per user or per groups. Для того чтобы назначить роли на  каждого из членов группы, из User делаем селект по group_id, после каждому назначаем желаемую роль.

> Все ще не зрозуміле призначення таблиці service. Чому сервіс посилається на ТО, а не навпаки? 

Немного путаюсь с отношениями между таблицами =) Сейчас исправлю.

> Як знайти інформацію, який саме сервіс присутній у конкретному ТО (як знайти який саме нащадок від service)?

Если Customer выбирает какого-либо из наследников Service, джойним предка (Service) и наследника по PrimaryKey, соответственно выгребаем всю полагающуюся инфу. Тот же принцип относится ко всем CRUD операциям.

> Як я зрозумів у таблиці service зберігаються уже оформлені замовлення на сервіси. А де зберігається інформація про власне сервіси (тарифи, максимальний час замовлення, максимальна кількість машин у замовленні тощо)?

Подразумевалось, что в сервисе и его наследниках будет хранится информация о сервисах, а окончательная цена будет формироваться в ТО. Таблицы не до конца заполнены, думаю, встретимся - допилим.

> У ТО повинна бути інформація як про машину, так і про водія, адже водій надалі може змінити машину і втратиться інформація.

Думаю, когда Драйвер заассайнит на себя ТО, то уже нет смысла ему менять машину. 

> Прив'язку водія до машини бажано мати типу багато-до-багатьох із зазначенням періоду (коли адмін призначив і коли зняв водія).

Сделал многие-ко-многим. Дату назначения сегодня доставим, не уверен, куда ее прикрепить.

> Не всі опціональні сервіси присутні. Для сервісу celebration немає зв'язку з конкретним набором машин, є лише кількість.

Проставил связь Car -> Celebration. Или лучше с водителем связать? Не могу обнаружить недостающих опциональных сервисов. На встрече разберемся =)

> Немає підтримки кількох адрес, ні опціонально у звичайному замовленні, ні у обов'язковому сервісі із доставки співробітників.

Теперь у таблицы Address есть поле тип (to | from | intermediate).

Надеюсь, теперь более-менее лучше. Спасибо за критику

**Comment by illia-tss** [comment]
а схему то забыл: http://www.gliffy.com/go/publish/7825579

**Comment by Rokill** [comment]
Илья, для реализации нескольких адресов, думаю, надо добавить в Address поле next_adress:int FK, ссылающийся на след. пункт назначения, след. Address. (связный список выйдет).

**Comment by illia-tss** [comment]
Интересная мысль! Добавил в Route initial_address_id, в Address добавил next_address_id, убрал тип адреса: http://www.gliffy.com/go/publish/7825579

**Comment by vchekaliuk** [comment]
Кілька нових коментарів.
1. Коли адмін редагує права, йому повинні показуватись поточні права цієї групи, тому треба, щоб ці дані десь зберігались. Права на звіти (reports) у вимогах ніяк не підпорядковуються ролям.
2. Персональні адреси не повинні бути пов'язані з конкретним ТО. Якщо користувач змінить або видалить свою адресу, то інформація про точку призначення ТО не може і не повинна змінюватись..
3. Про сервіси. Як ми у своїх запитах можемо наперед знати, якого саме нащадка джойнити? Тут така ж ситуація, як при касті типів у програмі та перевірці на instance of.
4. Кожна послуга повинна мати свої параметри, їх все ще немає. Наприклад, тариф за кожну машину в ескорті, максимальна кількість годин, на які можна замовити довготривале таксі, тощо. Так само, як є окрема таблиця з тарифами в залежності від часу доби, дня тощо.
5.Водій може змінити машину через місяць після ТО, коли це зробить адмін. При цьому інформація про минулі ТО, тобто історія, не повинні змінюватись.
6. Не зрозуміле призначення таблички driver option. Інформація про водія повинна зберігатись у табличці водія, а при підборі водія повинне виконуватись порівняння параметрів у ТО та параметрів водія. Те саме і щодо таблички car option. Ціну (надбавку до тарифу) додаткових вимог або машини слід зберігати там, де й інші тарифи.
7. Не вистачає, наприклад, сервісу доставки їжі, доставки гостя (не з аеропорту).
8. Не 100% впевнений, але здається driver як сутність не повинен бути дочірнім від user. Тобто user - це табличка для ідентифікації користувачів сайту, включаючи й адмінів, і водіїв. На її базі буде формуватись security. А driver - це уже сутність, що описує роль у системі, і доступ до неї отримую отримують лише юзери з відповідною роллю. Звичайно, посилання сутності водія на відповідну сутність юзера повинно бути.

**Comment by illia-tss** [comment]
крайняя версия: http://www.gliffy.com/go/publish/7865949

**Comment by illia-tss** [comment]
еще одна крайняя версия =) http://www.gliffy.com/go/publish/7865949

**Comment by illia-tss** [comment]
> Про сервіси. Як ми у своїх запитах можемо наперед знати, якого саме нащадка джойнити? Тут така ж ситуація, як при касті типів у програмі та перевірці на instance of.

У предка есть поле service_name. Предлагаю туда записывать имя определенного наследника. Тогда при поиске сервиса делаем SELECT service_name FROM Service WHERE service_id = ????, а потом уже обращаемся к нужной таблице по имени.

**Comment by illia-tss** [comment]
угадайте, что? правильно, еще [одна](http://www.gliffy.com/go/publish/7865949) =)

**Comment by arturstorm** [comment]
Навіщо таблиця tss_group?

**Comment by illia-tss** [comment]
показывает, какие группы пользователей в системе есть.
