### ISSUE TITLE
Project module structure

### ISSUE THREAD

**Issue by bbuallbest** [tss-ta/tss#37]
#### First vision of structure:

![tss-modules-structure](https://cloud.githubusercontent.com/assets/6570648/7108110/417237a0-e184-11e4-8371-ca1b7bfc0430.png)

**Comment by olga-tss** [comment]
У тебя получилось задеплоить EAR в JBoss на OpenShift-е?

**Comment by bbuallbest** [comment]
Получилось. Вот проект, который деплоил https://github.com/bbuallbest/ejb2-jpa-openshift. Только есть сомнения, соответствуют ли используемые в этом проекте EJB, версии 2.0...

**Comment by olga-tss** [comment]
@bbuallbest, хочу обсудить с тобой вот что.
Смотри, я сегодня собиралась донастроить и проверить функционирование проекта, развёрнутого на Опеншифте, такую себе, затравку от начала и до конца (вот заассайненная на меня [задача](https://github.com/tss-ta/tss/issues/5)). Т. е. сделать тестовую таблицу в БД, сделать тестовую сущность, получить DataSource, сделать сервис, вывести содержимое таблицы на странице. Кроме того, убедиться, что Дженкинс правильно собирает билд и деплоит приложение.
Я это собиралась делать для начала на одномодульном мэйвеновском проекте (такой, который создаётся по умолчанию при создании аппликейшна на Опеншифте). На этом этапе добавлять несколько модулей не планировала, чтобы не усложнять.
Если твой проект из нескольких модулей по пушу успешно билдится и деплоится в опеншифте, то можем взять его структуру за основу. Если пока нет - то давай я за сегодня закончу то, что собиралась, и у нас будет проверенная рабочая правильно деплоящаяся через Дженкинс начальная версия проекта, а ты уже потом расширишь её, сделав несколько модулей.

Также мне не очень понятно из твоей диаграммы вот что:
- как ты хочешь делать REST-UI? На каком-то JavaScript-фреймворке?
- зачем нам EAR? Если у нас только один WAR, то нам достаточно указать JAR как зависимость для WAR-ника. Другое дело, если мы будем делать несколько WAR-ников. Мы будем это делать? Для чего будет каждый?
- в твоём проекте используется хайбернейт. В ТЗ написано фреймворки на сервер-сайде не использовать.

**Comment by bbuallbest** [comment]
> Если твой проект из нескольких модулей по пушу успешно билдится и деплоится в опеншифте, то можем взять его структуру за основу. Если пока нет - то давай я за сегодня закончу то, что собиралась, и у нас будет проверенная рабочая правильно деплоящаяся через Дженкинс начальная версия проекта, а ты уже потом расширишь её, сделав несколько модулей.

По пушу, проект билдится и деплоится, только вот Jenkins у меня в этом процессе не участвует. 

> как ты хочешь делать REST-UI? На каком-то JavaScript-фреймворке?

Были мысли об jQuery, т.к. проще всего порог входа(в сравнении с Angular.js/Backbone.js/etc). Как результат, на нем сможет писать, практически, любой член комманды.

> зачем нам EAR? Если у нас только один WAR, то нам достаточно указать JAR как зависимость для WAR-ника. Другое дело, если мы будем делать несколько WAR-ников. Мы будем это делать? Для чего будет каждый?

Подразумевалось, что каждый прямоугольник - это отдельный модуль. 
Т.о. имеем два модуля:
- WEB-CLIENT - статические ресуры(html/js/css/img/..) + контроллер, для их обработки
- RES-API - rest контроллеры, отдающие json-ы + security(и да, я бы выбрал Spring Security, заместо JAAS)

Почему именно так? если использовать *.jsp с EL (пример - ${request.name}), так или иначе прийдется где-то кидать AJAX-ом запросы(к примеру при pagination-е), которые будут возвращять JSON-ы.. т.е. таки прийдется писать рест контроллеры.. 

> в твоём проекте используется хайбернейт. В ТЗ написано фреймворки на сервер-сайде не использовать.

В ТЗ написано:

> Front-end development (Java, JavaScript, HTML, CSS). No Java frameworks should be used , JS frameworks are allowed.

Hibernate не шибко похож на фреймворк для Front-end development-а на джаве =)

**Comment by olga-tss** [comment]
Если не возражаешь, я тогда доделаю то, о чём я говорила — оно в любом случае должно быть сделано. А ты потом сможешь перевести проект в мультимодульный (я маякну, когда закончу).

Хотя, может быть, надо обсудить разбивку на модули, REST и т. д. с командой? Вдруг у них другое мнение, или не все смогут разобраться с предложенной тобой реализацией пользовательского интерфейса. Голосовалку, что ли, сделать какую-то на Гугл-доках.

На мой субъективный взгляд, хайбернейт использовать нельзя, т. к. мы должны писать на технологиях, используемых в Неткрекере, а они, по-моему, хайбернейт не используют.

Если ты уже разобрался, как к бесплатному аккауту на Опеншифте подключить разработчиков — расскажи, и я подключу тебя. Если ещё не разобрался и хочешь помочь — посмотри, пожалуйста и поделись результатом. Насколько я пока поняла (но глубоко вникнуть я не успела и могу ошибаться) бесплатный аккаунт не поддерживает командную работу напрямую. Но я могу добавить твой SSH-ключ в аккаунт, и ты получишь такие же права, как и я. Но лучше было бы всё-таки, если бы можно было создать team и более гибко управлять правами доступа.

Если будешь делать какую-то задачу, то было бы классно, если бы ты ассайнил её на себя, если она есть в списке issue, а если она пока не заведена — то создал бы и заассайнил. Если мы все будем придерживаться такого подхода, то будет очень классно — будет сразу видно, кто какой задачей занимается, что уже сделано, а что ещё нет.

**Comment by bbuallbest** [comment]
> Если не возражаешь, я тогда доделаю то, о чём я говорила — оно в любом случае должно быть сделано. А ты потом сможешь перевести проект в мультимодульный (я маякну, когда закончу).

Ок)

> Хотя, может быть, надо обсудить разбивку на модули, REST и т. д. с командой? Вдруг у них другое мнение, или не все смогут разобраться с предложенной тобой реализацией пользовательского интерфейса. Голосовалку, что ли, сделать какую-то на Гугл-доках.

Для этого и создал issue, что бы все желающие высказали свое мнение/виденье)

> На мой субъективный взгляд, хайбернейт использовать нельзя, т. к. мы должны писать на технологиях, используемых в Неткрекере, а они, по-моему, хайбернейт не используют.

Нужно у лидов спросить, гадать нет смысла)

> Если ты уже разобрался, как к бесплатному аккауту на Опеншифте подключить разработчиков — расскажи, и я подключу тебя...

На практике не проверял, но пишут что можно https://help.openshift.com/hc/en-us/articles/202398940-Collaborative-Development-on-OpenShift

**Comment by olga-tss** [comment]
> На практике не проверял, но пишут что можно

Если хочешь, скинь мне свой логин (мыло, с которым ты зарегался на Опеншифте), и я добвлю тебя в аккаунт.

**Comment by Rokill** [comment]
Как мне помнится нам Hibernate разрешили пользоваться кураторы (в четверг).

**Comment by olga-tss** [comment]
@bbuallbest, всё ещё не закончила полностью свою задачу. Запушила промежуточный результат — сделала несколько модулей, глядя в т. ч. и на твой пример, тестовую сущность, простой тест. Хочу таки доделать [задачу](https://github.com/tss-ta/tss/issues/5). Думаю, за сегодня справлюсь.
