### ISSUE TITLE
REP.3 - Reports. The system should create RI reports: 

### ISSUE THREAD

**Issue by Rokill** [tss-ta/tss#87]
The system should create RI reports: 
- Most profitable taxi service of the week, month, decade
- Most popular car and driver category
- Most popular additional car options for each customer user
- Most popular additional car options overall

Reports should be available to restricted user groups.

**Comment by maks0** [comment]
have done:
Most popular additional car options for each customer user
Most popular additional car options overall

**Comment by maks0** [comment]
Most popular car category report have done
