### ISSUE TITLE
How about frameworks and libraries

### ISSUE THREAD

**Issue by bbuallbest** [tss-ta/tss#98]
Со структурой базы, +/- определились. С разбиением на модули, тоже.
Настало время решить, какие фреймворки и либы будем использовать.

Условные обозначения:
(+) - преимущество
(-) - недостаток

Лично я это себе представляю так:
### Веб слой

jQuery:
- (+) Простой как бревно 

JSP:
- (+) EL 
- (+) Директива include (можно отделить footer/header/etc)
- (-) Сложнее верстать (в сравнении с pure HTML), если нет hot swap-a 

~~Spring MVC:~~
~~(+) Меньше кода писать вручную.~~
~~(+) Гибкий URL маппинг (в сравнении с сервлетами)~~
~~(+) Легкий в использовании~~
~~(-)  Сложнее настройка (в сравнеии с сервлетами)~~
### Authentication and Authorization

Spring Security: 
- (+) Гибкость (к примеру, не нужно так жестко подстраивать схему бд, в отличии от Realm-ов)
- (+) Есть свой taglib для JSP 
- (-) Конфигурация, также может понадобится написание своих менеджеров/хендлеров/etc
### Бизнес слой

EJB 2.0 (ибо требование)
### Слой работы с БД

JPA(Hibernate/EclipseLink/etc):
- (+) На ней быстрее разрабатывать
- (+) Меньше кода писать вручную (в сравнении с JDBC)
- (-) Накладывает ограничения на структуру БД 
- (-) Требует неких, легконагугливаемых, познаний от разработчика  

Ниже, высказывайте свои предложения, пожелания, виденья..=)

**Comment by maks0** [comment]
достойное решение. Поскольку возражений нет, то давайте придерживаться этому подходу! Конфигурировать спринг сейчас будем "дедовским" способом на основе xml.
